apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-kubernetes-gitops
  namespace: argocd
spec:
  project: default
  source:
    # When you push this to your own GitHub, replace this URL with your GitHub repo URL
    repoURL: 'https://github.com/dilip0007/helm-argocd-pipeline.git'
    targetRevision: HEAD
    path: hello-kubernetes
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hello-kubernetes-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
